on:
  pull_request:
    branches:
      - main

jobs:
  should_i_deploy:
    runs-on: ubuntu-latest
    name: A job to check if you should deploy today
    steps:
      - name: Should I deploy?
        uses: lucoceano/shouldideploy-action@v11